# Generated by Django 4.0.1 on 2022-04-24 18:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('number', models.PositiveIntegerField(max_length=45)),
                ('zipcode', models.IntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Zipcode')),
                ('city', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
