# Generated by Django 4.0.1 on 2022-04-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
    ]
