# Generated by Django 4.0.1 on 2022-04-24 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(default=0, max_length=5, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Zipcode'),
            preserve_default=False,
        ),
    ]
